import {useEffect} from "react";
import Head from 'next/head'
import {useTheme} from 'next-themes'

import {
    Courses,
    Education,
    Experience,
    Header,
    Home,
    Interests,
    Languages,
    Profile,
    ScrollTop,
    Skills
} from "../components";

export default function Index() {
    const {theme, setTheme} = useTheme()

    useEffect(() => {
        setTheme('light')
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main className='md:py-6'>
                <div className='pb-16 md:pb-0 px-4 md:px-0 md:grid md:grid-cols-[2fr_4fr] md:gap-x-10
                 max-w-[968px] mx-auto md:bg-container md:shadow-md'>

                    {/*resume left*/}
                    <div className='md:bg-container-alt md:px-4'>
                        <Home/>
                        <Profile/>
                        <Education/>
                        <Skills/>
                    </div>

                    {/*resume right*/}
                    <div className='md:py-6'>
                        <Experience/>
                        <Courses/>
                        <Languages/>
                        <Interests/>
                    </div>

                </div>
                <ScrollTop/>
            </main>
        </>
    )
}
